version: "3"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:123456@mongodb:27017/?maxPoolSize=20&w=majority
      - JWT_SECRET=123
    ports:
      - "80:3000"
    volumes:
      - ./app:/code
